# Generated by Django 5.0 on 2024-12-19 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ez_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ops', 'Operations User'), ('client', 'Client User')], default=datetime.datetime(2024, 12, 19, 19, 2, 17, 127092, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
    ]
